server:
  port: 8081
spring:
  jpa:
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://localhost:3306/vacina?createDatabaseIfNotExist=true&allowPublicKeyRetrieval=true&sslMode=DISABLED
    password: root
    username: root
